### ISSUE TITLE
Hero Point Timer - Reset

### ISSUE THREAD

**Issue by git-kor-av** [xdy/xdy-pf2e-workbench#97]
Choosing the option to "Reset To" and selecting ALL seems to not set the value in the box, but add the value in the box.

Settings and values before reset:
![before-reset-to](https://user-images.githubusercontent.com/32276185/151662944-d155713d-13f4-452b-a768-a7567b4f6e25.jpg)

Values after reset:
![after-reset-to](https://user-images.githubusercontent.com/32276185/151662967-baf86f74-1682-4ee1-bd6b-6a919216c288.jpg)

**Comment by xdy** [comment]
Fixed by version 2.23.2 yesterday.

**Comment by git-kor-av** [comment]
So I updated to 2.23.3 and it definitely feels better, however it still doesn't seem quite right.  

Steps taken:

1. Have multiple characters, hero point levels shouldn't matter as long as they have at least 1.
2. Bring up the Hero Point helper window
3. Select Reset to, This many = 0, then choose All, Timer value shouldn't matter for this example
4. Hit the Submit changes with no Timer... 

You will see that all Characters do drop down to 0 after several seconds (if you have the sheets open you will see this on each character one at a time),  but if you keep the sheet open you will see that the hero points will then reset to 1 shortly there after.

It almost feels like reset has two loops... the first sets the value to whatever, then a second loop runs and adds one to it.

**Comment by xdy** [comment]
Yeah, something funky going on. I'll need to take another look at this. Thanks for looping back!
